### ISSUE TITLE
useEffect dependecy array

### ISSUE THREAD

**Issue by ibraheemazam** [rfp2209-trix/FEC#80]
https://github.com/rfp2209-trix/FEC/blob/a2efcc18ffabc98b91b6a54cd088a978d1254339/client/src/overview/imageGallery/imageGalleryMain.jsx#L26

Keep in mind if useEffect is used without a dependency array, it will run on every re-render. Be sure this is what you want.

**Comment by ColeMatthewBienek** [comment]
Noted. Thank you for the tip. I fished out the right dependencies and added them.
